server:
  port: 8888

#General Configuration
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          watch: true

  profiles:
    active:
    - native
management:
  endpoints:
    web:
      exposure:
        include:
          - 'refresh'